### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by AnteraTres** [vendethiel/reader.d2o#1]
Hi! I'm not too god with Json, so i need to ask. I put all the .d2o files into the data folder, and execute t.php with XAMPP, it gets a few seconds and then nothing ._. i'm doing something wrong? I need this :s

Thanks.

**Comment by vendethiel** [comment]
Just use the generated/ folder.

**Comment by AnteraTres** [comment]
:S But i need the 2.13 folder, and i will need more in a time :/ i was searching for a few days and only found this for .d2o :/ Q _ Q I need u

**Comment by vendethiel** [comment]
install node.js and run this command beforehand

```
npm install LiveScript
```
